### ISSUE TITLE
Support Windows SDK versions lower than 10

### ISSUE THREAD

**Issue by alastairUK** [Microsoft/TestAdapterForGoogleTest#19] opened 2017-08-08 12:58 UTC
VS2017 Professional 15.2 (26430.16) - Create a New Project - select 'Google Test' - enter project name 'GoogleTestBugReport' - make sure "create directory for solution" and "Create new Git repository" are selected.

Select "Static Library (.lib) " and "Link dynamically (Recommended). 

Get error Creating project 'GoogleTestBugReport' ... project creation failed

and no project created

**Comment by LukaszMendakiewicz** [comment] 2017-08-09 20:30
I cannot reproduce this issue. Perhaps we need to collect more diagnostics.

**Comment by alastairUK** [comment] 2017-08-09 21:53
Is there an error log file somewhere? Tried creating projects in multiple directories and no success.

**Comment by spebl** [comment] 2017-08-10 00:35
Hi! The most common issue to cause this is not having the Windows SDK installed. We seem to have a bug where this error message isn't properly showing to users and the project creation just quietly fails in this case. If you could check in the Visual Studio installer, click Modify on your installation and on the right hand side under "Desktop development with C++", please make sure one of the Windows 10 SDK options are checked off and installed. If so, and the issue persists, we can investigate further. We are currently working on fixing the error messages in failure cases, thanks!

**Comment by csoltenborn** [comment] 2017-08-10 04:27
Could this maybe be avoided by (additionally) adding an according entry to the `Prerequisites` section of the `.vsixmanifest` file?

**Comment by alastairUK** [comment] 2017-08-10 06:31
I don't have the Windows 10 SDK installed as I have limited SSD space and don't need it. Why does this extension require it?

**Comment by LukaszMendakiewicz** [comment] 2017-08-10 16:28
To be precise, it is not the extension that requires Windows 10 SDK, but only the project template part of the extension. If you do not have Windows 10 SDK installed, do you have Windows 8.1 SDK? If you create Win32 Console Application project from a template, what Windows SDK Version do you set it to?

**Comment by alastairUK** [comment] 2017-08-10 22:32
I use 8.1

**Comment by LukaszMendakiewicz** [comment] 2017-08-11 05:07
@spebl can we fall back to 8.1 if 10 is not found? This seems to be what Win32 Console Application template is doing (even if 8.1 is not installed).

**Comment by spebl** [comment] 2017-08-14 23:38
Having the windows SDK as a prerequisite is hard since we want people to be able to bring any version of it. I'll look into it and see if there's an option there. Currently I'm looking into why the 8.1 sdk isn't working now. We should definitely support that!

**Comment by spebl** [comment] 2017-08-15 22:00
Tested and checked in the fix for this. 8.1 SDK should now work properly, as well as an error message will be displayed if you have no SDK at all. Thanks for the feedback!

**Closed by spebl** 2017-08-15 22:00 UTC
Labels: bug
