### ISSUE TITLE
Build errors with C++17

### ISSUE THREAD

**Issue by yonni12** [Microsoft/TestAdapterForGoogleTest#120] opened 2018-02-09 21:01 UTC
Compiling my projects with the C++17 standard (`/std:c++17`) results in many compiler errors C2039 and C3083: "'tr1': is not a member of 'std'" and "tr1': the symbol to the left of a '::' must be a type"

This seems to be because the `tr1` namespace has been deprecated. While Google Test seem to have fixed it on their master branch, but this fix hasn't found it's way to TAFGT.

If the issue is with an upstream dependency, perhaps there is a temporary workaround for using the latest code from the Google Test repo?

**Comment by LukaszMendakiewicz** [comment] 2018-02-09 22:23
Duplicate of #119

**Closed by LukaszMendakiewicz** 2018-02-09 22:23 UTC
Labels: duplicate

**Comment by yonni12** [comment] 2018-02-09 22:26
Not exactly a duplicate. #119 refers to warnings. This refers to errors that render the adapter useless

**Comment by LukaszMendakiewicz** [comment] 2018-02-09 23:23
Thanks for clarification, I've updated #119 to be clear about that. Both have the same root cause, so we will use the older one to track it.

**Comment by LukaszMendakiewicz** [comment] 2018-02-09 23:32
Please also note that the adapter does not require you to use the Google Test version bundled in the provided NuGet packages. If you are OK using a version that's not tagged for a release (latest of which we provide), you could possibly pick one of the later commits from the Google Test repo, which I believe have the issue of using `std::tr1` fixed.
